apiVersion: jalapeno.srv6/v1
kind: PathRequest
metadata:
  name: l3vpn-example
spec:
  platform: linux  # or vpp
  vrfs:
    - name: customer1
      tableId: 0  # Optional, defaults to 0
      ipv4:
        routes:
          - name: customer1-vpn-routes
            route_target: "9:9"
            # Optional: specific prefix to query
            prefix: "9.9.9.0"  
            # Optional: exact match for prefix
            exact_match: false
            # Collection to query (default: l3vpn_v4_prefix)
            collection: "l3vpn_v4_prefix"
            outbound_interface: "ens4"  # For Linux
            #bsid: "fd00:100::1"  # For VPP
      # ipv6:
      #   routes:
      #     - name: customer1-vpn-routes-v6
      #       route_target: "15:15"
      #       collection: "l3vpn_v6_prefix"
      #       outbound_interface: "eth0"  # For Linux
      #       bsid: "fd00:100::2"  # For VPP
